name: Test
on:
  pull_request:
    branches:
    - main

jobs:
  seed_utils:
    name: Test Seed Utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm t seedUtils.test.js

  app_utils:
    name: Test App Utils
    runs-on: ubuntu-latest
    needs: seed_utils
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: testDatabase
          postgresql user: testUser
          postgresql password: testPassword

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: PGDATABASE=testDatabase PGUSER=testUser PGPASSWORD=testPassword npm t appUtils.test.js
  
  app:
    name: Test App
    runs-on: ubuntu-latest
    needs: app_utils
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/London"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: testDatabase
          postgresql user: testUser
          postgresql password: testPassword

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: PGDATABASE=testDatabase PGUSER=testUser PGPASSWORD=testPassword npm t app.test.js

  live_db:
    name: Test Live Database
    runs-on: ubuntu-latest
    needs: app
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/London"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: NODE_ENV=production DATABASE_URL=${{ secrets.DATABASE_URL }} npm t app.test.js
